In [1]:
import pandas as pd
import numpy as np

In [2]:
metadata = pd.read_csv('/home/atc009/biocurate/data/pfs_months.txt', sep='\t')
metadata

,PATIENT_ID,DRUG,DRUG_CLASS,START_DATE,END_DATE,PFS_DATE,PFS_MONTHS,PFS_STATUS
0,P-0000012,CARBOPLATIN,Chemo,61,68,281,7.227332,1:PROGRESSION
1,P-0000012,CISPLATIN,Chemo,33,40,281,8.147175,1:PROGRESSION
2,P-0000012,CYCLOPHOSPHAMIDE,Chemo,-5437,-5369,10,178.942181,1:PROGRESSION
3,P-0000012,ETOPOSIDE,Chemo,33,65,281,8.147175,1:PROGRESSION
4,P-0000012,FLUOROURACIL,Chemo,-5437,-5326,10,178.942181,1:PROGRESSION
...,...,...,...,...,...,...,...,...
105153,P-0089672,DOXORUBICIN,Chemo,-55,-13,170,7.395868,0:CENSORED
105154,P-0089672,FLUOROURACIL,Chemo,1,99,170,5.556183,0:CENSORED
105155,P-0089672,METHOTREXATE,Chemo,1,99,170,5.556183,0:CENSORED
105156,P-0089690,LETROZOLE-RIBOCICLIB,Other,-80,182,182,8.611676,0:CENSORED
105157,P-0089690,LEUPROLIDE,Hormone,-91,182,182,8.973043,0:CENSORED

In [4]:
survival = pd.read_csv('/home/atc009/biocurate/data/OS_time_adjusted.txt', sep='\t')
survival_treatment = pd.merge(survival, metadata[['PATIENT_ID', 'DRUG']], on='PATIENT_ID')
survival_treatment

       PATIENT_ID          SAMPLE_ID   OS_MONTHS   OS_STATUS              DRUG
0       P-0000012  P-0000012-T03-IM3  118.454665    0:LIVING       CARBOPLATIN
1       P-0000012  P-0000012-T03-IM3  118.454665    0:LIVING         CISPLATIN
2       P-0000012  P-0000012-T03-IM3  118.454665    0:LIVING  CYCLOPHOSPHAMIDE
3       P-0000012  P-0000012-T03-IM3  118.454665    0:LIVING         ETOPOSIDE
4       P-0000012  P-0000012-T03-IM3  118.454665    0:LIVING      FLUOROURACIL
...           ...                ...         ...         ...               ...
105753  P-0009406  P-0009406-T01-IM3   33.764347  1:DECEASED   INVESTIGATIONAL
105754  P-0009406  P-0009406-T01-IM3   33.764347  1:DECEASED          OLAPARIB
105755  P-0009406  P-0009406-T01-IM3   33.764347  1:DECEASED        PACLITAXEL
105756  P-0009406  P-0009406-T01-IM3   33.764347  1:DECEASED     PEMBROLIZUMAB
105757  P-0009406  P-0009406-T01-IM3   33.764347  1:DECEASED   ZOLEDRONIC ACID

[105758 rows x 5 columns]

In [6]:
patient2ind = pd.read_csv('/home/atc009/biocurate/data/patient2ind_msk.txt', sep='\t')
patient2ind = patient2ind.rename(columns={'sample':'SAMPLE_ID'})
patient2ind.to_csv('/home/atc009/biocurate/data/patient2ind.txt', sep='\t', index=None)

final_metadata = survival_treatment.merge(patient2ind, on='SAMPLE_ID')
final_metadata

,PATIENT_ID,SAMPLE_ID,OS_MONTHS,OS_STATUS,DRUG,index
0,P-0000012,P-0000012-T03-IM3,118.454665,0:LIVING,CARBOPLATIN,13185
1,P-0000012,P-0000012-T03-IM3,118.454665,0:LIVING,CISPLATIN,13185
2,P-0000012,P-0000012-T03-IM3,118.454665,0:LIVING,CYCLOPHOSPHAMIDE,13185
3,P-0000012,P-0000012-T03-IM3,118.454665,0:LIVING,ETOPOSIDE,13185
4,P-0000012,P-0000012-T03-IM3,118.454665,0:LIVING,FLUOROURACIL,13185
...,...,...,...,...,...,...
101554,P-0009406,P-0009406-T01-IM3,33.764347,1:DECEASED,INVESTIGATIONAL,23821
101555,P-0009406,P-0009406-T01-IM3,33.764347,1:DECEASED,OLAPARIB,23821
101556,P-0009406,P-0009406-T01-IM3,33.764347,1:DECEASED,PACLITAXEL,23821
101557,P-0009406,P-0009406-T01-IM3,33.764347,1:DECEASED,PEMBROLIZUMAB,23821
101558,P-0009406,P-0009406-T01-IM3,33.764347,1:DECEASED,ZOLEDRONIC ACID,23821

In [15]:
final_metadata.to_csv('/home/atc009/biocurate/data/patient_metadata.txt', sep='\t', index=None)

In [8]:
gene2ind = pd.read_csv('/home/atc009/biocurate/data/gene2ind_ctg_av.txt', sep='\t', header=None, names=['index', 'GENE_NAME'])
gene2ind.to_csv('/home/atc009/biocurate/data/gene2ind.txt', sep='\t', index=None)

In [12]:
cell2cna= pd.read_csv('/home/atc009/biocurate/data/cell2cnamplification_msk.txt', skiprows=1, header=None, index_col=False, names=gene2ind['GENE_NAME'].values)
cell2cna.index = patient2ind['SAMPLE_ID'].values
cell2cna

,ABCB1,ABCC3,ABL1,ABL2,ACTA2,ACVR1B,ADGRA2,AJUBA,AKT1,AKT2,...,YEATS4,ZBTB2,ZFHX3,ZNF217,ZNF471,ZNF620,ZNF703,ZNF750,ZNRF3,ZRSR2
P-0081657-T01-IM7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0083825-T01-IM7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0085255-T02-IM7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0000106-T01-IM3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0088122-T01-IM7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P-0005845-T01-IM5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0007174-T01-IM5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0009470-T01-IM5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0013992-T01-IM5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
P-0014611-T01-IM6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
cell2cna.to_csv('/home/atc009/biocurate/data/cell2cnamplification_labeled.txt', sep='\t')

In [14]:
cell2cnd= pd.read_csv('/home/atc009/biocurate/data/cell2cndeletion_msk.txt', skiprows=1, header=None, index_col=False, names=gene2ind['GENE_NAME'].values)
cell2cnd.index = patient2ind['SAMPLE_ID'].values
cell2cnd.to_csv('/home/atc009/biocurate/data/cell2cndeletion_labeled.txt', sep='\t')

cell2mut= pd.read_csv('/home/atc009/biocurate/data/cell2mutation_msk.txt', skiprows=1, header=None, index_col=False, names=gene2ind['GENE_NAME'].values)
cell2mut.index = patient2ind['SAMPLE_ID'].values
cell2mut.to_csv('/home/atc009/biocurate/data/cell2mutation_labeled.txt', sep='\t')